### ISSUE TITLE
Naslov v README datoteki

### ISSUE THREAD

**Issue by katjabercic** [siskadavid/racunalniski-praktikum#1]
V README.md datoteki v prvi vrstici piše `# Računalniski praktikum`, moralo bi pisati `# Računalniški praktikum`. Če popravite, boste dobili točko.

Lep pozdrav,
Katja

**Comment by siskadavid** [comment]
Pozdravljeni!

Sem popravil in committal spremembo, ali moram tudi še enkrat  oddati v spleni učilnici?

Lp, David
________________________________
From: Katja Berčič ***@***.***>
Sent: Monday, October 21, 2024 9:43 AM
To: siskadavid/racunalniski-praktikum ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [siskadavid/racunalniski-praktikum] Naslov v README datoteki (Issue #1)


V README.md datoteki v prvi vrstici piše # Računalniski praktikum, moralo bi pisati # Računalniški praktikum. Če popravite, boste dobili točko.

Lep pozdrav,
Katja
